//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GpsCtrl.rc#define IDS_PROJNAME 100
#define IDR_GPSCTRL 101
#define IDR_GPS 102
#define IDR_GPSCONSTANTS 103
#define IDR_GPSPROJECTION 104
#define IDR_GPSGRIDPARAMETERS 105
#define IDR_GPSDATUMPARAMETERS 106
#define IDR_GPSSATELLITEINFO 107
#define IDR_GPSUTILITIES 108
#define IDR_TABLE_DATUMS 200
#define IDR_TABLE_GRIDS 201

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 201
#define _APS_NEXT_COMMAND_VALUE 32768
#define _APS_NEXT_CONTROL_VALUE 201
#define _APS_NEXT_SYMED_VALUE 109
#endif
#endif
